export type Product = {
  id: string;
  sku: string;
  name: string;
  author: string;
  shortDesc: string;
  fullDesc: string;
  price: number;
  category: string;
  format: "Hardcover" | "Paperback";
  pages: number;
  isbn: string;
};

export const products: Product[] = [
  {
    id: "CK-FIC-001",
    sku: "CK-FIC-001",
    name: "The Midnight Archive",
    author: "Elena Marchetti",
    shortDesc: "A chilling mystery set in a secret underground library holding the world's most dangerous books.",
    fullDesc: "When archivist Rowan Adeyemi discovers a locked section of the Midnight Archive, she unwittingly sets off a chain of events that will change the course of history. A masterfully plotted thriller with razor-sharp twists, stunning prose, and an unforgettable heroine.",
    price: 26.99,
    category: "Fiction & Mystery",
    format: "Hardcover",
    pages: 387,
    isbn: "978-1-234567-01-1",
  },
  {
    id: "CK-BUS-001",
    sku: "CK-BUS-001",
    name: "Building Empires from Zero",
    author: "Kwame Asante",
    shortDesc: "The definitive playbook for taking your idea from zero to seven figures.",
    fullDesc: "Entrepreneur and investor Kwame Asante breaks down the exact frameworks, mental models, and daily disciplines used by the world's most successful founders. No fluff — just proven systems you can implement starting today.",
    price: 22.50,
    category: "Business & Entrepreneurship",
    format: "Paperback",
    pages: 312,
    isbn: "978-1-234567-02-8",
  },
  {
    id: "CK-SLF-001",
    sku: "CK-SLF-001",
    name: "The Quiet Mind",
    author: "Dr. Amara Osei",
    shortDesc: "A science-backed guide to calming anxiety and building lasting mental clarity.",
    fullDesc: "Drawing on decades of clinical research and mindfulness practice, Dr. Amara Osei delivers a compassionate, practical roadmap for those who feel overwhelmed by the noise of modern life. Includes 30 exercises you can begin immediately.",
    price: 18.99,
    category: "Self-Help & Wellness",
    format: "Paperback",
    pages: 256,
    isbn: "978-1-234567-03-5",
  },
  {
    id: "CK-SCI-001",
    sku: "CK-SCI-001",
    name: "Chronicles of the Deep",
    author: "J.R. Hollingsworth",
    shortDesc: "An epic sci-fi saga where humanity's last survivors colonise the ocean floor.",
    fullDesc: "Five hundred years after the surface world burned, the city of Abyssal sprawls across the Pacific floor. But when a young engineer discovers a signal from above, old wounds — and old wars — are ripped open. A breathtaking world-building triumph.",
    price: 28.00,
    category: "Sci-Fi & Fantasy",
    format: "Hardcover",
    pages: 504,
    isbn: "978-1-234567-04-2",
  },
  {
    id: "CK-BUS-002",
    sku: "CK-BUS-002",
    name: "The Negotiator's Playbook",
    author: "Sophia Lin",
    shortDesc: "Master the psychology of persuasion to win every deal, raise, and negotiation.",
    fullDesc: "Former Fortune 500 negotiator Sophia Lin reveals the hidden scripts, strategic pauses, and power plays used in high-stakes deals worldwide. Whether you're negotiating a salary, a contract, or a peace treaty, these principles apply.",
    price: 21.99,
    category: "Business & Career",
    format: "Paperback",
    pages: 278,
    isbn: "978-1-234567-05-9",
  },
  {
    id: "CK-SLF-002",
    sku: "CK-SLF-002",
    name: "Untangle Your Space",
    author: "Mei-Ling Torres",
    shortDesc: "A warm, illustrated guide to decluttering your home and simplifying your life.",
    fullDesc: "Interior designer and minimalist advocate Mei-Ling Torres takes you room by room through a gentle, sustainable decluttering process. Features beautiful hand-drawn illustrations and practical checklists that make the process feel like a joy, not a chore.",
    price: 24.99,
    category: "Self-Help & Lifestyle",
    format: "Hardcover",
    pages: 224,
    isbn: "978-1-234567-06-6",
  },
  {
    id: "CK-ROM-001",
    sku: "CK-ROM-001",
    name: "Smoke and Starlight",
    author: "Adaeze Nwosu",
    shortDesc: "A sweeping historical romance set in 1920s Lagos at the height of the jazz age.",
    fullDesc: "Brilliant seamstress Funmi falls for a mysterious trumpet player whose past holds a secret that could destroy everything they've built. A gorgeous, lush novel overflowing with music, longing, and the intoxicating atmosphere of a city on the edge of change.",
    price: 19.99,
    category: "Romance & Historical Fiction",
    format: "Paperback",
    pages: 358,
    isbn: "978-1-234567-07-3",
  },
  {
    id: "CK-EDU-001",
    sku: "CK-EDU-001",
    name: "The Python Cookbook",
    author: "Femi Adebayo",
    shortDesc: "250 practical recipes to solve real-world problems in Python 3.12.",
    fullDesc: "Stop Googling your way through Python. This comprehensive cookbook covers everything from file manipulation and web scraping to machine learning pipelines and async programming. Each recipe is self-contained, battle-tested, and ready to drop into your project.",
    price: 34.99,
    category: "Technology & Education",
    format: "Hardcover",
    pages: 618,
    isbn: "978-1-234567-08-0",
  },
  {
    id: "CK-NON-001",
    sku: "CK-NON-001",
    name: "Plant Power Kitchen",
    author: "Ngozi Eze",
    shortDesc: "90 bold, high-protein plant-based recipes designed for Nigerian and West African palates.",
    fullDesc: "Nutritionist and food writer Ngozi Eze proves that plant-based eating doesn't mean sacrificing the rich, complex flavours of West African cuisine. Jollof rice, egusi, suya-spiced dishes — all re-imagined without compromise.",
    price: 29.99,
    category: "Food & Lifestyle",
    format: "Hardcover",
    pages: 288,
    isbn: "978-1-234567-09-7",
  },
  {
    id: "CK-SCI-002",
    sku: "CK-SCI-002",
    name: "The Glass Kingdom",
    author: "Tobias Vance",
    shortDesc: "A dark fantasy of assassins, prophecies, and a kingdom built on beautiful lies.",
    fullDesc: "In the Crystal City, beauty is currency and truth is treason. When a disgraced assassin is tasked with protecting the very ruler who destroyed her family, she must choose between vengeance and something far more dangerous — hope.",
    price: 25.50,
    category: "Sci-Fi & Fantasy",
    format: "Hardcover",
    pages: 432,
    isbn: "978-1-234567-10-3",
  },
  {
    id: "CK-BUS-003",
    sku: "CK-BUS-003",
    name: "Money Made Simple",
    author: "Chidi Okonkwo",
    shortDesc: "A clear, no-jargon guide to personal finance, investing, and building wealth in Nigeria.",
    fullDesc: "Certified financial planner Chidi Okonkwo walks you through budgeting on any income, navigating Nigerian investment vehicles (Treasury Bills, Eurobonds, real estate), and building a wealth strategy that actually fits your life.",
    price: 17.99,
    category: "Business & Finance",
    format: "Paperback",
    pages: 234,
    isbn: "978-1-234567-11-0",
  },
  {
    id: "CK-FIC-002",
    sku: "CK-FIC-002",
    name: "The Raising of Dragons",
    author: "Saoirse Flynn",
    shortDesc: "A young dragon tamer must prevent a war between the five dragon clans and humanity.",
    fullDesc: "Fifteen-year-old Kira has a gift no one believes in — until the day she hatches the last dragon egg in existence. Now hunted by three kingdoms and mentored by an exiled warlord, she has one season to forge a peace that has eluded generations.",
    price: 22.99,
    category: "Fantasy & Young Adult",
    format: "Hardcover",
    pages: 396,
    isbn: "978-1-234567-12-7",
  },
];
